<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Animale</name>
   <tag></tag>
   <elementGuidId>d2ee7bdb-1415-478b-9d2e-33185a4cc21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butonAnimale']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>663a1df2-c79b-487c-8062-63c2221d37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue</value>
      <webElementGuid>da515c35-77a4-48ff-ac70-785a5d41733c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Animale</value>
      <webElementGuid>da07c7ae-5d98-4767-bdf3-0bf1aa48dd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butonAnimale&quot;)/p[@class=&quot;blue&quot;]</value>
      <webElementGuid>81676f15-2add-429b-8550-357bef80721f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butonAnimale']/p</value>
      <webElementGuid>42b43f2f-5639-42d6-922d-8e67b71ca4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorii'])[2]/following::p[2]</value>
      <webElementGuid>8251505a-21f2-40cd-835c-38373c015331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[2]</value>
      <webElementGuid>dfb75e4e-b8f3-47e3-9b32-d770744ef395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/preceding::p[6]</value>
      <webElementGuid>70f3f8f4-9c25-4dcf-9f41-b7fe0f2035d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Animale']/parent::*</value>
      <webElementGuid>92d8abfa-ac5f-4aad-b8ad-31755dd19d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>8fd6918a-ddcb-45bc-a9b7-1f02d0b8c221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Animale' or . = 'Animale')]</value>
      <webElementGuid>08189350-c972-4697-a5c1-33dd26cf01cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
