<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Mancare</name>
   <tag></tag>
   <elementGuidId>55fed0b3-1a5a-4e82-8060-1a0f7acf9c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butonMancare']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#butonMancare > p.blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6d2f74c0-4e4b-4317-82f9-f06351be9c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue</value>
      <webElementGuid>b8d28cb1-d3f5-4469-a308-872423a214db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mancare</value>
      <webElementGuid>8c5a8dd7-2b64-47ae-995a-c73176a64a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butonMancare&quot;)/p[@class=&quot;blue&quot;]</value>
      <webElementGuid>105c2460-c959-4b1f-9894-935fba57f287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butonMancare']/p</value>
      <webElementGuid>fe0b730a-a39b-47cb-bacf-ae8a9156ad6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorii'])[2]/following::p[4]</value>
      <webElementGuid>6ba0b9b6-bf05-4c0c-a70d-3ffb3dd62357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[4]</value>
      <webElementGuid>0fd25e83-db4c-4ebf-acae-0345e7277721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/preceding::p[4]</value>
      <webElementGuid>8c6376ae-a9dc-4e32-ba93-91ba0ce412bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mancare']/parent::*</value>
      <webElementGuid>dddd6d61-d60e-4743-b05a-2a4514818771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/button/p</value>
      <webElementGuid>ecdcb58f-7caf-4e90-8264-080635cb25d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Mancare' or . = 'Mancare')]</value>
      <webElementGuid>76cbec76-1441-439d-b35e-01dcae8dc5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
