<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Orase</name>
   <tag></tag>
   <elementGuidId>08f6772e-6359-4f78-83d0-5c0318d5a486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butonOrase']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#butonOrase > p.blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ddeb998c-fa22-44ff-baa2-5d9113dee9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue</value>
      <webElementGuid>6f9c8cdb-9f9e-4719-b550-798ce2761dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orase</value>
      <webElementGuid>b3450511-b423-4042-962a-3dd4b637c6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butonOrase&quot;)/p[@class=&quot;blue&quot;]</value>
      <webElementGuid>9f0ed06b-b6df-4078-8e40-49d9d06dd8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butonOrase']/p</value>
      <webElementGuid>5c63e296-e09d-45c2-a2f9-8041dcc92ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorii'])[2]/following::p[6]</value>
      <webElementGuid>d2e1675e-6b79-44c5-aa6d-16d055feb0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[6]</value>
      <webElementGuid>a7787d36-f998-4f07-8032-581dbf562f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/preceding::p[2]</value>
      <webElementGuid>b5d4f4fa-f7ff-4963-8b33-0f119268f910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orase']/parent::*</value>
      <webElementGuid>15aa20f9-3fea-4880-8e19-857268ea45e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/button/p</value>
      <webElementGuid>55c73243-f3c1-439a-be7e-9db7e41fcbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Orase' or . = 'Orase')]</value>
      <webElementGuid>9d06b50a-59d7-4edf-88b3-ba5001451c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
