<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Portrete</name>
   <tag></tag>
   <elementGuidId>acc69743-5250-43d8-9871-5e33153c8499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butonPortrete']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#butonPortrete > p.blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>065fa5bc-47f9-4260-b483-927c69eff62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue</value>
      <webElementGuid>b27f1604-cb41-462e-bbf0-6e80abbdcde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portrete</value>
      <webElementGuid>37fc7a3f-9393-4da8-99db-1658cde834c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butonPortrete&quot;)/p[@class=&quot;blue&quot;]</value>
      <webElementGuid>8cbc2882-be60-4c8e-b8ba-b7c6ccccb12e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butonPortrete']/p</value>
      <webElementGuid>f53f3e14-5b69-4a84-9e68-353f1bbc37e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorii'])[2]/following::p[7]</value>
      <webElementGuid>2ea11db7-9cb1-4cd0-9651-8728f3f32ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[7]</value>
      <webElementGuid>e3bf478d-9474-4112-a44a-3ed0c237d9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/preceding::p[1]</value>
      <webElementGuid>951af927-384b-4eea-ae7e-010e17ad3544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Portrete']/parent::*</value>
      <webElementGuid>d47d95cf-efe8-4e28-b1a8-29afab7616de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/button/p</value>
      <webElementGuid>304c271b-fbb1-4b29-8d29-7afb4d7a0e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Portrete' or . = 'Portrete')]</value>
      <webElementGuid>2b6c4ecc-b4f3-4516-bc52-48e759033741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
