<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descriere_Descriere</name>
   <tag></tag>
   <elementGuidId>c3a3d42f-6229-48cd-8307-f9664dc69d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Descriere</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Descriere']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdfa0b6e-ea28-43e1-9f97-d419e4e1bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42d6c749-1490-45db-a159-d1eae7e865e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48aed024-1ee2-4b33-a030-a08055a94094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Descriere field is required.</value>
      <webElementGuid>746a5357-f06e-487f-abdb-bae85c3fc0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Descriere</value>
      <webElementGuid>c938ad5d-db66-4211-aba7-1a8166d7ab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Descriere</value>
      <webElementGuid>d142d5bb-fd5f-4a3a-abb8-a7b640d96f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Descriere&quot;)</value>
      <webElementGuid>1cc98cbd-3dd9-40c3-bd0e-2613e3db7876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Descriere']</value>
      <webElementGuid>eba398e8-c234-49d3-a61b-a096ee79dbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6c35a65c-4bab-4d38-aec5-118d00775a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Descriere' and @name = 'Descriere']</value>
      <webElementGuid>81ce80c3-c6db-4ecd-92c1-c9d15572783b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
