<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_Input.Password</name>
   <tag></tag>
   <elementGuidId>59ca34bf-4c77-4bfb-a77b-b6d0cfc0bc52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5b5fdc6-9999-4b48-97b8-20d828c0374a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-black</value>
      <webElementGuid>5782b9f2-38da-420f-889c-37d6c3d25263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>3c2367de-2bc6-4ab4-8fb5-9aed74709a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73f202eb-a29b-4c7f-bdba-da68e184be69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a04f0b62-d601-4621-92f2-b1637fab0c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>068079bc-c44c-4db1-9390-5a93c35de7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Password field is required.</value>
      <webElementGuid>34d0ca27-e305-42a1-b29f-aafadc7e9c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Password</value>
      <webElementGuid>ba85aeca-7319-47de-b8cd-68c4b40b73d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Password</value>
      <webElementGuid>19a7371c-c54d-4d17-a298-683c0bf807a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Password&quot;)</value>
      <webElementGuid>456ae7e7-c569-4d2d-9983-b4898db285e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Password']</value>
      <webElementGuid>a6ca8b9b-1b67-4bae-a377-e0cdd846ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div[2]/input</value>
      <webElementGuid>68198f37-32cb-4249-93f6-1b27dac24b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fdf11f1e-320d-4103-98f6-87207b695c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Input_Password' and @name = 'Input.Password']</value>
      <webElementGuid>08b290c8-8eaa-4eb4-ba0b-09c5eca3b529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
