<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Editare</name>
   <tag></tag>
   <elementGuidId>0b44a03f-5686-485e-afdd-2885d41d4c84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Editare')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7) > a.text-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d16017f9-78bb-455e-a54c-8b544df57e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-light</value>
      <webElementGuid>d69d0a3d-b673-43e1-95dc-eac6693e12f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Poze/ShowEditarePoza/1</value>
      <webElementGuid>4f1cfe0f-6a85-4c49-80e9-7c648e912e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editare</value>
      <webElementGuid>ba34ac12-cd9a-4df2-bf75-055b2a2bbe80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;text-light&quot;]/td[7]/a[@class=&quot;text-light&quot;]</value>
      <webElementGuid>3862b0bd-6c6f-4ea5-9661-6e81e87cf926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Editare')]</value>
      <webElementGuid>d3d9c39e-405a-4343-b0db-3ed0aff243aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user2@email.com'])[1]/following::a[1]</value>
      <webElementGuid>0cad36b4-707a-4e82-a81b-0bf98491ffa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalii'])[1]/preceding::a[1]</value>
      <webElementGuid>d93b88f9-9d30-4053-9e3b-7e1204fdbc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sterge'])[1]/preceding::a[2]</value>
      <webElementGuid>a20574e0-8e00-4b81-baa7-c661f33977b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editare']/parent::*</value>
      <webElementGuid>2c81bcd8-9748-4bdf-84c7-86b81d73be0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Poze/ShowEditarePoza/1')]</value>
      <webElementGuid>d2eb85d2-c4ac-4716-9e99-d326bf071952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>c93c276d-b364-47bc-bab5-7d5f1098aae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Poze/ShowEditarePoza/1' and (text() = 'Editare' or . = 'Editare')]</value>
      <webElementGuid>f8255513-7462-43d5-b107-cb8017bca0ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
