<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Reset_thumbnailPoza</name>
   <tag></tag>
   <elementGuidId>b9121720-6e28-4f08-8166-3f7e02fbeb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.thumbnailPoza</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>731cfcd6-b8d1-4d0c-8f55-6b592ed2e8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumbnailPoza</value>
      <webElementGuid>e445898d-d8d4-4577-8f77-c3d4aa6e18b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Imagini/ImaginiUploadate/Animale/pupper - 2023-05-04-09-42-05.8869.jpg?v=aWIN1Gz2biQFyTOwBtRUM9EkvZqyb4UGPUy_uZLXYw4</value>
      <webElementGuid>380401d6-f886-4955-95e4-c2b0f2999e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/main[1]/div[@class=&quot;toatePozele&quot;]/a[1]/img[@class=&quot;thumbnailPoza&quot;]</value>
      <webElementGuid>06ca4fe3-e037-4aa1-b56b-6510611c4ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1d2f212a-fe3e-442c-86ca-5778addce7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
